name: holy_messages
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.2.0
  home_widget: ^0.5.0
  path_provider: ^2.0.0

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  intl: ^0.20.2
  share_plus: ^12.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.1.0
  google_mobile_ads: ^5.0.0
  in_app_purchase: ^3.2.3
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.0
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^6.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.0
  permission_handler: ^11.0.0
  image: ^4.0.0
  google_fonts: ^6.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.10
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/data/
    - assets/icon/
    - assets/splash/
    - assets/backgrounds/
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"
  remove_alpha_ios: true

# flutter_native_splash:
#   color: "#FFFFFF"
#   image: assets/splash/open.png
#   android: true
#   ios: true
#   web: false
#   fullscreen: true
#   ios_content_mode: scaleAspectFit
#   android_gravity: fill
#   android_12:
#     color: "#FFFFFF"
#     image: assets/splash/open.png
#     fullscreen: true